import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/components/navbarUser";
import Footer from "@/components/footer";
import NextAuthSession from '../nextAuthSession';

export const metadata: Metadata = {
  title: "Pizza Hut",
  description: "Generated by Pizza Hut",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <main className="felx-grow">
          <NextAuthSession>
          <Navbar />
          {/* Main content area */}
          {children}
          <Footer/>
        </NextAuthSession>
        </main>
      </body>
    </html>
  );
}

